### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by andrewghobrial** [rifflock/lfshook#37]
Hi, I'm getting this panic that seems to be caused by this code in this project:

```
panic: runtime error: slice bounds out of range

goroutine 8 [running]:
internal/poll.(*FD).Write(0xc4201ba140, 0xc420552000, 0x7b, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:219 +0x535
os.(*File).write(0xc42033e018, 0xc420552000, 0x7b, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:233 +0x90
os.(*File).Write(0xc42033e018, 0xc420552000, 0x7b, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:140 +0x106
github.com/rifflock/lfshook.(*lfsHook).fileWrite(0xc420064200, 0xc4201ba0f0, 0x0, 0x0)
	/Users/gmendel/GO/src/github.com/rifflock/lfshook/lfshook.go:150 +0x706
github.com/rifflock/lfshook.(*lfsHook).Fire(0xc420064200, 0xc4201ba0f0, 0x0, 0x0)
	/Users/gmendel/GO/src/github.com/rifflock/lfshook/lfshook.go:86 +0x9d
github.com/sirupsen/logrus.LevelHooks.Fire(0xc420080c90, 0xc400000004, 0xc4201ba0f0, 0x0, 0x0)
	/Users/gmendel/GO/src/github.com/sirupsen/logrus/hooks.go:28 +0xfa
github.com/sirupsen/logrus.Entry.log(0xc42008e1e0, 0xc42052c060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4, ...)
	/Users/gmendel/GO/src/github.com/sirupsen/logrus/entry.go:98 +0x19d
github.com/sirupsen/logrus.(*Entry).Info(0xc4201ba0a0, 0xc42036bf90, 0x1, 0x1)
	/Users/gmendel/GO/src/github.com/sirupsen/logrus/entry.go:144 +0xd9
github.ibm.com/Bluemix/cf-admin-agent/utils/logger.(*Logger).log(0x29bbcb8, 0x2, 0xc42027e104, 0xc42036bf90, 0x1, 0x1)
...
```

Any idea what might cause this?

**Comment by rifflock** [comment]
What version are you running? That stack trace doesn't seem to be lining up with the line numbers in the latest version.

The only thing I can think is that there's an issue with the `[]levels`, as that's the only slice in this hook. Can you post how you initialize your hook?

**Comment by rifflock** [comment]
Closing for inactivity
